### ISSUE TITLE
ElvUI skinning issue

### ISSUE THREAD

**Issue by MSav93** [DengSir/tdBattlePetScript#24] opened 2020-09-01 11:39 UTC
This is an issue brought up on the curseforge page I'm just rewriting it here so it's tracked and resolved properly.

![image](https://user-images.githubusercontent.com/5080453/91844543-023f2480-ec9b-11ea-8fd0-9afd9fa38194.png)

A solution discovered by Minstril43 on curseforge involves not creating "ArtFrame2" if ElvUI is active and skinning the pet battle UI.
See workaround here: https://www.curseforge.com/wow/addons/tdbattlepetscript?comment=89

**Comment by sylvanas1408** [comment] 2021-03-02 18:31
hi，it didn't work，can u upload your changed file：petbattle.lua，i amnot sure i changed it right

**Comment by bloerwald** [comment] 2022-10-28 16:46
Duplicate of #50.

**Closed as completed** 2022-10-28 16:55 UTC
