### ISSUE TITLE
ability.duration in combination with <,> and ~ bug

### ISSUE THREAD

**Issue by cosinussinus** [DengSir/tdBattlePetScript#37] opened 2020-12-01 14:16 UTC
TDScript doesn't work if you use ability.duration  with <, > if the pet with this ability isn't active.

Example:
Your **active** pet is a rabbit (1/2/1)
TD Script:
use(Dodge:312)
use(Burrow:159) [self.ability(Dodge:312).duration<3]
use(#1)

Fight:
Round 1: Dodge
Round 2: ability 1
Round 3: ability 1
Round 4 Burrow
... --> This one works fine

Now the buggy version
Your **active** pet is a Emerald-Proto-Whelp (2/2/2) (Emerald bite/Emerald Presence/Emerald Dream)
TD Script: (Same one)
use(Dodge:312)
use(Burrow:159) [self.ability(Dodge:312).duration<3]
use(#1)
Fight:
Round 1: Script is doing nothing  --> normally (old Version 8) the script will do "use(#1)"

edit: This issue is caused by the following change:
https://github.com/DengSir/tdBattlePetScript/commit/d99b9f0256d1eb2a5f2caa1d57403332e8c250fc

**Comment by bloerwald** [comment] 2020-12-14 19:21
Duplicate of https://github.com/DengSir/tdBattlePetScript/issues/26

**Comment by mutanzoom** [comment] 2021-06-07 07:01
Unfortunately I have the problem too. :( You use the option very often.
Such as: _ability(Ghostly Bite: 654) [enemy.ability (Mudslide: 572) .duration <5]_ 
 Unfortunately, that doesn't work either.

**Comment by cosinussinus** [comment] 2021-06-11 13:18
> Unfortunately I have the problem too. :( You use the option very often.
> Such as: _ability(Ghostly Bite: 654) [enemy.ability (Mudslide: 572) .duration <5]_
> Unfortunately, that doesn't work either.

 There is a workaround for this issue. You have to add the enemy who has the ability. in your case:
ability(Ghostly Bite: 654) [enemy(#1).active & enemy.ability (Mudslide: 572) .duration <5] 
It's just a temporary solution. I hope that will be fixed one day ...

**Comment by mutanzoom** [comment] 2021-06-11 16:02
Hello, now I already have this solution. But it's still a shame that the author is not working on the addon. He wrote me by email that he was too busy for this addon. When I wrote back that I would like to donate something to him and whether the donation link is still up to date, unfortunately nothing came back ... :(

Do you have a solution for my latest problem?
I always have such a wooden box as an Elvui user: https://github.com/DengSir/tdBattlePetScript/issues/50

**Comment by axc450** [comment] 2022-10-26 23:26
> Hello, now I already have this solution. But it's still a shame that the author is not working on the addon. He wrote me by email that he was too busy for this addon. When I wrote back that I would like to donate something to him and whether the donation link is still up to date, unfortunately nothing came back ... :(
> 
> Do you have a solution for my latest problem? I always have such a wooden box as an Elvui user: #50

I am looking after this addon now. I will try and fix this soon :)

**Closed as completed** 2022-10-28 16:55 UTC
